### ISSUE TITLE
Support for tracing other AmqpTemplate send methods 

### ISSUE THREAD

**Issue by sudr** [opentracing-contrib/java-spring-rabbitmq#11]
The @Around advice currently limits to tracing to just one of the send methods where exchange, routingKey and message are passed as arguments.

This appears quite limiting. Is there a reason for this? Can we expand this pointcut to include other send methods as well?

https://github.com/opentracing-contrib/java-spring-rabbitmq/blob/904bd38465c790a362740ceb8cf4f7f532d35ada/opentracing-spring-rabbitmq/src/main/java/io/opentracing/contrib/spring/rabbitmq/RabbitMqSendTracingAspect.java#L42

**Comment by wuyupengwoaini** [comment]
The same confusion about these

**Comment by ask4gilles** [comment]
Fixed by https://github.com/opentracing-contrib/java-spring-rabbitmq/pull/9 `org.springframework.amqp.rabbit.core.RabbitTemplate.sendAndReceive` and `org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceive` will be in 0.1.1

**Comment by ask4gilles** [comment]
Fixed by https://github.com/opentracing-contrib/java-spring-rabbitmq/pull/9 `org.springframework.amqp.rabbit.core.RabbitTemplate.sendAndReceive` and `org.springframework.amqp.rabbit.core.RabbitTemplate.convertSendAndReceive` will be in 0.1.1
