### ISSUE TITLE
Enhancement request: Support for DirectMessageListenerContainer when using RabbitMqReceiveTracingInterceptor

### ISSUE THREAD

**Issue by sudr** [opentracing-contrib/java-spring-rabbitmq#13]
Currently the RabbitMqBeanPostProcessor registers the RabbitMqReceiveTracingInterceptor for SimpleMessageListenerContainer. This request is to enhance  RabbitMqBeanPostProcessor to support the DirectMessageListenerContainer.

https://github.com/opentracing-contrib/java-spring-rabbitmq/blob/904bd38465c790a362740ceb8cf4f7f532d35ada/opentracing-spring-rabbitmq/src/main/java/io/opentracing/contrib/spring/rabbitmq/RabbitMqBeanPostProcessor.java#L42

**Comment by ask4gilles** [comment]
@sudr Do you want to submit a PR for this?

**Comment by sudr** [comment]
Yes. I will submit one today.

**Comment by sudr** [comment]
I just realized that this will necessitate an upgrade to a minimum of Spring Boot 2.0 dependencies since the DirectMessageListenerContainer is only available beginning in spring-rabbit-2.0 which is available via Spring Boot 2.0 dependencies.

So this change will need to wait for the dependencies to be updated to Spring Boot 2.0 or later. Please let me know how we should proceed.

**Comment by ask4gilles** [comment]
I just tried to bump SB version, and after fixing some imports, it still breaks a lot of tests :/ 
So, I've created this separate [issue ](https://github.com/opentracing-contrib/java-spring-rabbitmq/issues/17)

**Comment by sudr** [comment]
I'll submit the PR for this once PR #19 is merged.

**Comment by ask4gilles** [comment]
> I'll submit the PR for this once PR #19 is merged.
@sudr feel free to add this to 1.0.0 so that I can perform a first release.
