### ISSUE TITLE
Send span instead of receive

### ISSUE THREAD

**Issue by msoub** [opentracing-contrib/java-spring-rabbitmq#14]
Hello,

Thanks for this module.

We are not sure why but it looks like `RabbitMqBeanPostProcessor` does not detect properly my message consumers. Therefore the spans are tagged as `send` instead of `receive`.

FYI we use `org.springframework.cloud.stream.annotation.StreamListener` to read the messages from RabbitMQ.

**Comment by ask4gilles** [comment]
Hi,
Can you provide a small use case somewhere?
Thx!

**Comment by ask4gilles** [comment]
Closing in lack of feedback. Please reopen and provide an example if needed.
