### ISSUE TITLE
Tracing isn't appearing in jaeger

### ISSUE THREAD

**Issue by monkeonman** [opentracing-contrib/java-spring-rabbitmq#27]
Hi,

I'm using the following method call:

this.template.convertAndSend("fanout.exchange", "", message);

But I'm seeing no tracing for RabbitMQ appear in my jaeger all in one instance.

I've added these to my pom:

		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
			<version>1.0.3</version>
		</dependency>

		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-rabbitmq-starter</artifactId>
			<version>1.0.1</version>
		</dependency>

I haven't defined a Tracer bean in my code, as I believe this is supplied by opentracing-spring-jaeger-cloud-starter.  I am seeing tracing for the API call I am making (when I did define the bean in my code, I wasn't even seeing that).

Any idea why I might not be seeing any tracing for the queue?

**Comment by ask4gilles** [comment]
Your dependencies are correct. (I'm currently using the same setup)

> I haven't defined a Tracer bean in my code, as I believe this is supplied by opentracing-spring-jaeger-cloud-starter.
That's correct also.

> when I did define the bean in my code, I wasn't even seeing that
Which bean?

Can you share a minimal example project somewhere?

**Comment by monkeonman** [comment]
Thanks for replying so quickly!  The Bean I was talking about was the Tracer bean that you'll see commented out in the MessagingApplication class in the repo below:

https://github.com/monkeonman/rabbitexample

Hopefully you'll be able to see what I'm doing wrong!

**Comment by ask4gilles** [comment]
so, you have to add:
```
  @Bean
  public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
    return new RabbitTemplate(connectionFactory);
  }
```
And it's fixed...We need to work on this, sorry about that.

![jaeger](https://user-images.githubusercontent.com/12292890/55631753-0e2e6a80-57b9-11e9-9f20-d5955276d859.png)

**Comment by monkeonman** [comment]
That's awesome, just confirmed that here too.

Glad it wasn't anything too dumb, might just be worth adding that to the README.  Thanks for your help!
