### ISSUE TITLE
OT 0.33+ compatibility

### ISSUE THREAD

**Issue by ask4gilles** [opentracing-contrib/java-spring-rabbitmq#32]

**Comment by GrahamLea** [comment]
FYI, java-spring-rabbitmq now fails while trying to trace if OT 0.33+ is on the classpath due to the removal of ScopeManager.active(), which is used in RabbitMqTracingUtils:
```
java.lang.NoSuchMethodError: io.opentracing.ScopeManager.active()Lio/opentracing/Scope;
at io.opentracing.contrib.spring.rabbitmq.RabbitMqTracingUtils.buildSendSpan(RabbitMqTracingUtils.java:58) ~[opentracing-spring-rabbitmq-2.0.5.jar:na]
```

**Comment by srinarayanant** [comment]
Hi @ask4gilles  , can you please help with work-around /versions which work together for now- 


		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-cloud-starter</artifactId>
			<version>0.3.11</version>
		</dependency>
		
		
		<dependency>
			<groupId>co.elastic.apm</groupId>
			<artifactId>apm-opentracing</artifactId>
			<version>1.12.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.opentracing</groupId>
			<artifactId>opentracing-api</artifactId>
			<version>0.33.0</version>
		</dependency>
		<dependency>
			<groupId>io.opentracing</groupId>
			<artifactId>opentracing-util</artifactId>
			<version>0.33.0</version>
		</dependency>

**Comment by ask4gilles** [comment]
@srinarayanant The latest version of this library is compatible with open tracing 0.32.0

**Comment by ask4gilles** [comment]
Fixed by https://github.com/opentracing-contrib/java-spring-rabbitmq/pull/47
