### ISSUE TITLE
RabbitMqTracingAutoConfiguration order

### ISSUE THREAD

**Issue by wuyupengwoaini** [opentracing-contrib/java-spring-rabbitmq#33]
RabbitMqTracingAutoConfiguration  should be created after  RabbitAutoConfiguration,otherwise ,RabbitMqSendTracingAspect can not be created

**Comment by wuyupengwoaini** [comment]
Because We still use springboot 1,5.x ,could you merge it to branch release-0.1?

**Comment by ask4gilles** [comment]
This has been backported to the release-0.1 branch.
