### ISSUE TITLE
No tracing data

### ISSUE THREAD

**Issue by wuyupengwoaini** [opentracing-contrib/java-spring-rabbitmq#35]
I use opentracing-spring-rabbitmq-starter of version 0.1.1,and I use RabbitTemplate to send mq message.
The code is following:
` this.rabbitTemplate.convertAndSend("hello", "hello");`

But I do not receive the producer and consumer span in Jaeger-UI.And then I debug and find that the RabbitMqSendTracingAspect does not take effect.

The root cause is that calls stack is 

`@Override
	public void convertAndSend(String routingKey, final Object object) throws AmqpException {
		convertAndSend(this.exchange, routingKey, object, (CorrelationData) null);
	}
  
	public void convertAndSend(String exchange, String routingKey, final Object object, CorrelationData correlationData) throws AmqpException {
		send(exchange, routingKey, convertMessageIfNecessary(object), correlationData);
	}`

The aspect is not cut in the method(convertAndSend(String routingKey, final Object object)) called

**Comment by ask4gilles** [comment]
@wuyupengwoaini I've to do some backporting from master. You should really consider upgrading your SB version which will be EOL August this year...

**Comment by wuyupengwoaini** [comment]
Yeah,It's better to upgrade my springboot version but there are many applications which are still use springboot 1.5.x in my company ,so the upgrading process is a long way

**Comment by wuyupengwoaini** [comment]
@ask4gilles  any progress?

**Comment by ask4gilles** [comment]
Not yet, I’m sorry but I didn’t take the time to do it yet. Hopefully, by the end of the week.

**Comment by ask4gilles** [comment]
@wuyupengwoaini can you test with 0.1.2-SNAPSHOT and let me know if it fixes your issue so that I can make a new release?

**Comment by wuyupengwoaini** [comment]
@ask4gilles   I'll test it today

**Comment by wuyupengwoaini** [comment]
@ask4gilles Have you posted the jar package of version 0.1.2-SNAPSHOT to the maven repository?

**Comment by ask4gilles** [comment]
@wuyupengwoaini no, you have to use the snapshot repo which is  
```
maven {
    url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
  }
```

**Comment by wuyupengwoaini** [comment]
@ask4gilles   0.1.2-SNAPSHOT is ok when it's in springboot 1.5.x env

**Comment by ask4gilles** [comment]
Release 0.1.2 has been published.
