### ISSUE TITLE
Tracer doesn't register the existing span

### ISSUE THREAD

**Issue by KishoreKaushal** [opentracing-contrib/java-spring-rabbitmq#38]
I have a code which starts a span before sending a message to RabbitMQ queue and then finishes the span. Something like this:

```
Span span = tracer.buildSpan("initApp").start();

rabbitTemplate.send( ... );

span.finish(); 
```

The expected tracing result should be:

```
Trace 1: initApp --> producer -->  ...   --> END
```
But the span initApp is created as a different trace. 
```
Trace 1: initApp --> END
Trace 2: producer -->  ...  --> END
```

I am using Jaeger implementation.

@ask4gilles  Correct me if my method is wrong. Kindly look through this.

**Comment by ask4gilles** [comment]
@KishoreKaushal please share a minimal project setup to reproduce the issue.

**Comment by ask4gilles** [comment]
@KishoreKaushal you forgot to activate the span with:
```
  tracer.scopeManager().activate(span);
```
![screen](https://user-images.githubusercontent.com/12292890/59089013-5f69f000-8909-11e9-8ef8-6d1bdcd03bce.png)
