### ISSUE TITLE
Consumer does not start an active span

### ISSUE THREAD

**Issue by tomasjad** [opentracing-contrib/java-spring-rabbitmq#41]
Hello,
It could be there is something I misunderstand in the concept of the library but I have an impression that an active span context should be started on message receive time (not on the send). Let me give you an example of what I do, my expectation and the actual result.
I have two microservices (call them A and B). A microservice listens on the queue (messages come from other parties I have no control on). When message arrives, service A, makes some insert to database and sends a message to message broker (message received by service B).
In this scenario I expect to see a single trace, which contains spans for all activities in both services A and B. Actual result is 2 different traces: one for service A:insert and another which contains everything for A and B except insert span for A.

 My attempt to change the behavior to meet my expectations looks following in RabbitMqTracingUtils class:

```
static Optional<Scope> buildReceiveSpan(MessageProperties messageProperties, Tracer tracer) {
    Optional<SpanContext> context = findParent(messageProperties, tracer);
    Tracer.SpanBuilder spanBuilder =
        tracer
            .buildSpan(RabbitMqTracingTags.SPAN_KIND_CONSUMER)
            .ignoreActiveSpan()
            .withTag(Tags.SPAN_KIND.getKey(), RabbitMqTracingTags.SPAN_KIND_CONSUMER);

    context.ifPresent(spanContext -> spanBuilder.addReference(References.FOLLOWS_FROM, spanContext));
    Scope scope = spanBuilder.startActive(true);

    return Optional.of(scope);
  }
```

Can you please give tell me whether there is something misunderstand in the usage of library or in my expectations or does my fix really makes sense?
PS. I use Jaeger implementation
Thank you!

**Comment by ask4gilles** [comment]
@tomasjad can you please provide a minimal sample project to reproduce the issue?

**Comment by tomasjad** [comment]
Demo services added:
https://github.com/tomasjad/demo-a.git
https://github.com/tomasjad/demo-b.git

Start both services, send anything to the queue "demo.start".
Prerequisites for RabbitMq (sorry for not automating this):

-  create exchange "demo.exchange"
- create queue "demo.start"
- create queue "demo.queueB", bind with exchange with routing key "demo.routingkeyB"
- create queue "demo.end", bind bind with exchange with routing key "demo.routingkeyEnd"

**Comment by ask4gilles** [comment]
fixed by https://github.com/opentracing-contrib/java-spring-rabbitmq/pull/42

**Comment by ask4gilles** [comment]
Thanks a lot @tomasjad, I just cut a 2.0.4 release. It should appear on maven central in a few.
I'll create a PR in opentracing-contrib/java-spring-cloud to update the dependency.
