### ISSUE TITLE
with Jaeger cloud does not support springboot 2.x

### ISSUE THREAD

**Issue by etherlai** [opentracing-contrib/java-spring-rabbitmq#44]
hi:
cause opentracing-spring-jaeger-cloud-starter 1.x support springboot 2.x.  I use springboot 2.0.x and opentracing-spring-jaeger-cloud-starter:1.03, but opentracing-spring-jaeger-cloud-starter incloud opentracing-spring-rabbitmq:0.1.0, 0.1.0 only support springboot 1.5.x.

**Comment by ask4gilles** [comment]
@etherlai either force the dependency version of the java-spring-rabbitmq to the latest or upgrade opentracing jaeger/spring-cloud version.
