### ISSUE TITLE
RabbitMqSendTracingAspect does not interfere in RestTemplate.invoke

### ISSUE THREAD

**Issue by huehnerlady** [opentracing-contrib/java-spring-rabbitmq#48]
Hi,

we use the following snippet for publishing messages:
```
rabbitTemplate.invoke({ RabbitOperations operations ->
      operations.convertAndSend(<EXCHANGE>, null as String, payload, defaultPublishMessagePostProcessor)
      operations.waitForConfirmsOrDie(DEFAULT_WAIT_TIMEOUT_IN_MS)
      return true
    })
```

Unfortunately the class `RabbitMqSendTracingAspect` does just interfere with the sending options of the rest template, but seems not to work inside the `invoke` method. We need this snippet to ensure that the message we send actually arrived on rabbitMQ.

Is there any plans to enhance the Aspect to also be able to work with our snippet?

**Comment by huehnerlady** [comment]
Anybody? 😞

**Comment by ask4gilles** [comment]
Hi @huehnerlady ,
Sorry but I don't have the time to look at this for the moment.
Feel free to submit a PR and I'll find the time to review it.

**Comment by huehnerlady** [comment]
@ask4gilles many thanks for your answer. 
Unfortunately I do not understand the Aspects well, but will see what I can do

**Comment by ask4gilles** [comment]
@huehnerlady alright, if you can come with something, I could find the time to help with that.
