### ISSUE TITLE
Spring AMQP 1.0 for RabbitMQ

### ISSUE THREAD

**Issue by hrirm** [opentracing-contrib/java-spring-rabbitmq#51]
Hello,

is there a plan to provide an implementation for protocol AMQP 1.0 with spring framework that would work with RabbitMQ ?

**Comment by ask4gilles** [comment]
What do you mean? Can you provide a bit more details about your need?

**Comment by hrirm** [comment]
I guess my issue is with rabbitMQ java client which is not supporting protocol AMQP 1.0

**Comment by ask4gilles** [comment]
This library just instruments for distributed tracing, not sure it’s the right place to raise your concern. Or perhaps can you be a bit more precise about what you need to do?

**Comment by hrirm** [comment]
I got a response here https://github.com/rabbitmq/rabbitmq-java-client/issues/652

It seems that I should consider to migrate to another broker 

Thanks for your support
