### ISSUE TITLE
opentracing-spring-rabbitmq usage

### ISSUE THREAD

**Issue by hodur** [opentracing-contrib/java-spring-rabbitmq#52]
I'm having trouble using this with Spring (no Boot). The only classes in `io.opentracing.contrib.spring.rabbitmq` that are public when using `<artifactId>opentracing-spring-rabbitmq</artifactId>` are:

1. RabbitMqSpanDecorator
2. RabbitMqTracingTags
3. RabbitMqSendTracingHelper

Looking at [RabbitMqTracingManualConfig](https://github.com/opentracing-contrib/java-spring-rabbitmq/blob/5feba50e6012d1e6e8614f7937ebf90ea5cd5b2e/opentracing-spring-rabbitmq-it/src/test/java/io/opentracing/contrib/spring/rabbitmq/RabbitMqTracingManualConfig.java) (which I want to emulate in my project) I'd need 

1. RabbitMqSendTracingAspect
2. RabbitMqReceiveTracingInterceptor
3. RabbitMqBeanPostProcessor
4. RabbitMqSpanDecorator

Which makes this impossible to use. Your integration tests work because they are in the same package.

Am I missing something? Is it not possible to use this without the Boot `-starter` version?

**Comment by hodur** [comment]
@ask4gilles created this [PR](https://github.com/opentracing-contrib/java-spring-rabbitmq/pull/53). I can't link the pull request and the issue.

**Comment by hodur** [comment]
@ask4gilles Could you release 3.0.1 with my changes?

**Comment by ask4gilles** [comment]
Sure, I’ll do my best to do it tomorrow

**Comment by ask4gilles** [comment]
I'm afraid I can't pushed the tag I've created for local security restrictions reasons. Maybe @pavolloffay Could give it a shot?

**Comment by hodur** [comment]
@pavolloffay any chance of releasing 3.0.1?

**Comment by ask4gilles** [comment]
@hodur I just released 3.0.1
